apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resource
  labels:
    app: nginx-resource

spec:
  replicas: 5

  selector:
    matchLabels:
      app: nginx-resource
  
  template:
    metadata:
      labels:
        app: nginx-resource
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi 