apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-with-configmap1
  labels:
   app: app1-with-configmap1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-with-configmap1

  template:
    metadata:
      labels:
        app: app1-with-configmap1
      
    spec:
      containers:
        - image: nginx
          name: app1-with-configmap1
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: app1-configmap
                  key: APP_MODE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app1-configmap
                  key: DB_HOST
          