apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1-secret
  labels:
    app: app1-secret

spec:
  replicas: 3

  selector:
    matchLabels:
      app: app1-secret
  
  template:
    metadata:
      labels:
        app: app1-secret
  
    spec:
      containers:
          - image: nginx
            name: nginx
            ports:
              - containerPort: 80

            env:
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: app1-secret
                    key: DB_USER

              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: app1-secret
                    key: DB_PASS