apiVersion: v1
kind: Pod
metadata: 
  name: storage-pod
  labels:
    app: storage-pod

spec:
  containers:
    - image: nginx
      name: nginx
      ports:
       - containerPort: 80

      volumeMounts:
        - name: app-storage
          mountPath: /app-data

  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: app-pvc